### ISSUE TITLE
jupyter notebook

### ISSUE THREAD

**Issue by skyap** [bitranox/wrapt-timeout-decorator#5]
* **I'm submitting a ... **
  - [ ] bug report
  - [ ] feature request
  - [ x] support request

* **What is the current behavior?**
when using it with jupyter notebook, not output is printed but output is printed if i run it in console. the code i test is as below:
import time
from wrapt_timeout_decorator import *

@timeout(5)
def mytest(message):
    import time
    print(message)
    for i in range(1,10):
        time.sleep(1)
        print('{} seconds have passed'.format(i))

if __name__ == '__main__':
    mytest('starting')
    print("finish")

* **Please tell us about your environment:**

- Version of wrapt-timeout-decorator : 
- Python Version : 3.6.2
- OS, OS Version : window 7

**Comment by bitranox** [comment]
Since mytest() is running in another process, You can not see it printing.
You might need to use sys.stdout.flush() after the print() statement.
See: https://stackoverflow.com/questions/2774585/child-processes-created-with-python-multiprocessing-module-wont-print

I have created now the "launch binder" badge, and a small Junyper Notebook, so You can test it online. 

Yours sincerely

Robert
