### ISSUE TITLE
 Accessing variables and modules from the function with decorator in Windows

### ISSUE THREAD

**Issue by gravitycode** [bitranox/wrapt-timeout-decorator#8]
* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [] support request

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**
if I try to use a variable or module in the function with the decorator, it tells me that it does not exist. In linux or mac it does works.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

```
from time import sleep
from wrapt_timeout_decorator import *

name="my_var_name"


@timeout(5, use_signals=False)
def mytest():
    print("Start ", name)
    for i in range(1,10):
        sleep(1)
        print("{} seconds have passed".format(i))
    return i


if __name__ == '__main__':
    mytest()
```
output: name 'name' is not defined
(the same occurs with sleep function)

* **What is the expected behavior?**
i want to have access to modules and vars

* **Please tell us about your environment:**

- Version of wrapt-timeout-decorator : 1.0.1 (master)
- Python Version :  3.7.2
- OS, OS Version :  Windows Server 2016

**Comment by bitranox** [comment]
its not a bug its a feature ;-)

On Windows the main module is imported again (but with __name__ != '__main__') because Windows is trying to simulate a forking-like behavior on a system that doesn't have forking. multiprocessing has no way to know that you didn't do anything important in you main module, so the import is done "just in case" to create an environment similar to the one in your main process. So the variable "name" and all functions You defined in the "main" are new objects - but the decorator refers to the "old" objects of the main process, so they cant be found.

It is more a problem of Windows, because the Windows Operating System does not support "fork".

here You can find more information on that : 

https://stackoverflow.com/questions/45110287/workaround-for-using-name-main-in-python-multiprocessing

https://docs.python.org/2/library/multiprocessing.html#windows

In general (especially for windows) , the main() program should not have anything but the main function, the real thing should happen in the libraries.
I am also used to put all settings or configurations in a different file - so all processes or threads can access them (and also to keep them in one place together, not to forget typing hints and name completion in Your favorite editor)

here an example that will work : 

```
my_program_main.py:

from multiprocessing import freeze_support
import lib_test

def main():
    lib_test.mytest()


if __name__ == '__main__':
    freeze_support()
    main()
```

```
conf_my_program.py:

class ConfMyProgram(object):
    def __init__(self):
        self.name:str = 'my_var_name'

conf_my_program = ConfMyProgram()

```

```
lib_test.py:

from wrapt_timeout_decorator import *
from time import sleep
from conf_my_program import conf_my_program

@timeout(5, use_signals=False)
def mytest():
    print("Start ", conf_my_program.name)
    for i in range(1,10):
        sleep(1)
        print("{} seconds have passed".format(i))
    return [{"id": 1}]

```

hope it helps, let me know.

**Comment by bitranox** [comment]
and thanks for the input - I put clarification into the README

**Comment by gravitycode** [comment]
Thank you so much @bitranox. Excellent explanation.
